_target_: ibc.optimizers2.LangevinMCMCSampler

noise_scale: 0.33
noise_shrink: 0.5
iters: 3
train_samples: 256
inference_samples: 2 ** 14
num_iterations: 25,
sampler_stepsize_init: 1e-1,
sampler_stepsize_decay: 0.8,
sampler_stepsize_final: 1e-5,
sampler_stepsize_power: 2.0,
use_polynomial_rate: True,
delta_action_clip: 0.1