_target_: train_manager.TrainingManager
_recursive_: false

defaults:
 - dataset: pixel_regression
 - test_dataset: test_pixelregression

seed: 42
max_epochs: 50
train_batch_size: 5
test_batch_size: 1
num_workers: 1