_target_: ibc.train_manager.TrainingManager
_recursive_: false

defaults:
 - dataset: pixel_regression
 - test_dataset: test_pixelregression

seed: 42
max_epochs: 2000
train_batch_size: 8
test_batch_size: 64
num_workers: 1
eval_every_n_steps: 1000